site_name: Analog Devices MSDK Documentation
site_author: Analog Devices
copyright: 'Copyright (C) Maxim Integrated Products, Inc., All rights Reserved.'
repo_url: https://github.com/Analog-Devices-MSDK/msdk
edit_uri: null
docs_dir: 'Documentation'
site_dir: 'docs'
nav:
  - Home: 'index.md'
  - User Guide: 'USERGUIDE.md'
  - Contributing: 'CONTRIBUTING.md'
  - License: 'LICENSE.md'
theme:
  name: readthedocs
markdown_extensions:
  codehilite:
    use_pygments: False