name: clang-format-run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  clang-format-run:

    # Do not run on Analog-Devices-MSDK/Libraries-miscDrivers:main branch
    if: |
      ${{ (github.ref != 'refs/heads/main' ||
      github.repository != 'Analog-Devices-MSDK/Libraries-miscDrivers') }}

    runs-on:
      - self-hosted
      - software

    steps:
      - name: Clean
        continue-on-error: true
        run: |
          # Remove local modifications
          set +e

          # Attempt to clean the repo
          git scorch
          retval=$?

          # Remove everything if this fails
          if [[ $retval -ne 0 ]]
          then
            rm -rf *
          fi

          set -e

      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
          # Only works on branches, not PRs.

      # Runs a set of commands using the runners shell
      - name: clang-format-run
        run: |

          bash -ex .github/workflows/clang-format-run.sh

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
