name: Uncrustify

on:
    issue_comment:
      # types: [created]

jobs:
    run_uncrustify:
      if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'Marie Kondo')
      runs-on: ubuntu-latest
      container: ros:foxy
      steps:
        - uses: xt0rted/pull-request-comment-branch@v1
          id: comment-branch
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
          with:
              path: repo
              ref: ${{ steps.comment-branch.outputs.head_ref }}
        - name: Style
          run: |
            # Exec Uncrustify
            cd repo
            . /opt/ros/$ROS_DISTRO/setup.sh && ament_uncrustify --reformat
            # Commit
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git commit -am "Uncrustified"
            git push
