name: BLE Verify TIFS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lock:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, btm-ci ]
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Lock Resources
        if: ${{ always() }}
        run: |
          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/$USER/Workspace/Resource_Share/max32655_0.txt
          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/$USER/Workspace/Resource_Share/max32655_1.txt
          
  verify:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, btm-ci ]
    needs: [ lock ] # Only run if the lock was successful
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false 

      - uses: actions/checkout@v3
        with:
          submodules: false
          repository: yc-adi/ble_auto_testing
          ref: main
          path: ble_auto_testing

      # Runs a set of commands using the runners shell
      - name: Build BLE5_ctr and flash to boards
        run: |
          echo `pwd`
          echo "\$GITHUB_WORKSPACE="$GITHUB_WORKSPACE
          bash /home/$USER/Workspace/BLE-examples-test/Examples_tests/verify_tifs.sh $GITHUB_WORKSPACE
          
      - name: Run test
        run: |
          cd $GITHUB_WORKSPACE/ble_auto_testing
          ls
          if [ -d ./output ]; then
            rm ./output/*
          else
            mkdir output
          fi
          echo "--------------"
          echo "Run TIFS test."
          echo "--------------"
          bash .github/workflows/run.sh

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: failure-report
            path: ble_auto_testing/output
      
      # Unlock even when cancelled or failed
      - name: unlock
        if: always()
        run: |
          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py /home/$USER/Workspace/Resource_Share/max32655_1.txt
          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py /home/$USER/Workspace/Resource_Share/max32655_0.txt
