name: clang-format-run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  clang-format-run:

    # Do not run on Analog-Devices-MSDK/msdk:main branch
    if: |
      !(github.ref == 'refs/heads/main' &&
      github.repository == 'Analog-Devices-MSDK/msdk')

    runs-on:
      - self-hosted
      - software

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          # Only works on branches, not PRs.
    
      - uses: actions/checkout@v3
        with:
          submodules: false

      # Runs a set of commands using the runners shell
      - name: clang-format-run
        run: |

          bash -ex .github/workflows/clang-format-run.sh

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
